#!/usr/bin/env bash
# Transfers a file from our client to a server
if [ "$#" != 3 ] && [ "$#" != 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

if [ "$#" -eq 4 ]
then
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
else
  scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
