#!/usr/bin/env bash
# Installs nginx web server and configues it

# Install nginx
echo "Installing nginx..."
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Making nginx serve "Hello World!" at its root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart nginx
echo "Restarting nginx..."
sudo service nginx restart

echo -e "Done!\n"
