#!/usr/bin/env bash
# Configures nginx server to redirect /redirect_me

# Install nginx
echo "Installing nginx..."
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Making nginx serve "Hello World!" at its root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Configure redirection
sudo sed -i 's/server_name daniel-kamel.tech;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx
echo "Restarting nginx..."
sudo service nginx restart

echo -e "Done!\n"
