#!/usr/bin/env bash
# Configures a new Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# Install nginx
echo "Installing nginx..."
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Start nginx service
sudo service nginx start

# Making nginx serve "Hello World!" at its root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Configure redirection
sudo sed -i '36i\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\t}' /etc/nginx/sites-available/default

# Configure 404 page
sudo bash -c echo "Ceci n'est pas une page > /var/www/html/error_404.html"
sudo sed -i '40i\\n\terror_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx
echo "Restarting nginx..."
sudo service nginx restart

echo -e "Done!\n"
