#!/usr/bin/env bash
# Configures a new Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# Install nginx
echo "Installing nginx..."
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Start nginx service
sudo service nginx start

# Making nginx serve "Hello World!" at its root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Configure redirection
sudo sed -i '47i\    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Configure 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '48i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx
echo "Restarting nginx..."
sudo service nginx restart

echo -e "Done!\n"
