#!/usr/bin/env bash
# Configure web-02 to be identical to web-01 and add
# 'X-Served-By' custom HTTP response header.

# Install nginx
echo "Installing nginx..."
sudo apt-get -y update
sudo apt-get -y install nginx

# Allow nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Start nginx service
sudo service nginx start

# Making nginx serve "Hello World!" at its root
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Configure redirection
redirect_line="$(printf '\t')""rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
if ! grep -Fxq "$redirect_line" /etc/nginx/sites-available/default
then
sudo sed -i "47i$redirect_line" /etc/nginx/sites-available/default
fi
# Configure 404 page
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
not_found_line="$(printf '\t')""error_page 404 /error_404.html;"
if ! grep -Fxq "$not_found_line" /etc/nginx/sites-available/default
then
sudo sed -i "48i$not_found_line" /etc/nginx/sites-available/default
fi

# Add 'X-Served-By' custom HTTP response header
custom_header="$(printf '\t')"'add_header X-Served-By $HOSTNAME;'
if ! grep -Fxq "$custom_header" /etc/nginx/sites-available/default
then
sudo sed -i "49i$custom_header" /etc/nginx/sites-available/default
fi

# Restart nginx
echo "Restarting nginx..."
sudo service nginx restart

echo -e "Done!\n"
