#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server

# Install HAproxy
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*

# Configure HAproxy
echo "
frontend http_front
  bind *:80
  mode http
  default_backend http_back
backend http_back
  balance roundrobin
  server 530987-web-01 35.174.204.185:80 check
  server 530987-web-02 54.237.8.132:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy
sudo service haproxy restart
