#!/usr/bin/env bash
# Fix Nginx server error by installing it
sudo apt-get -y update
sudo apt-get -y install nginx
sudo rm /etc/nginx/sites-enabled/*
ln -sf /etc/nginx/sites-available/* /etc/nginx/sites-enabled/
sudo service nginx restart
