#!/usr/bin/env bash
# Prints bad luck on the 4th iteration and good luck on
# the 8th iteration and Best School on the rest of the
# iterations
i=1
while [ $i -le 10 ];
do
    if ((i == 4))
    then
        echo "bad luck"
    elif
        ((i == 8))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
