#!/usr/bin/env bash
# Prints bad luck from China on the 4th iteration and
# good luck from Japan on the 8th iteration and bad
# luck from Italy the on the 17th iteration and number
# of the iteration on the rest of the iterations
i=1
while [ $i -le 20 ];
do
    case "$i" in

    4) echo "bad luck from China"
    ;;
    8) echo "good luck from Japan"
    ;;
    17) echo "bad luck from Italy"
    ;;
    *) echo "$i"
    ;;
    esac
    ((i++))
done
