#!/usr/bin/env bash
# The content of the current directory in a list format
# where only the part of the name after the first dash is displayed
lst=$(ls)
for line in $lst;
do
    echo "$line" | cut -d '-' -f2
done
